---
title: "Aspectos ambientais"
editor: visual
---

\[Em desenvolvimento\]

```{r, eval = FALSE, eval=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

library(readxl)
library(tidyverse)
meio_ambiente <- read_excel("bases/9 - MEIO AMBIENTE/IMRS - 2022/Base Plataforma 2022 (Nova)/IMRS_BASE_MEIO-AMBIENTE_2000-2021.xlsx")

library(readxl)
pop <- read_excel("bases/0 - POPULAÇÃO REFERÊNCIA/IMRS - 2022 (População Referência)/IMRS2022 - BASE POPULACAO REFERENCIA.xlsx") %>% select(IBGE7, ANO,AREA,D_DENSP)


df_nome <- readRDS("dados/df_nome.rds")

municipios_vale <- c(
  3103405,  # Araçuaí
  3112307,  # Capelinha
  3119500,  # Coronel Murta
  3133303,  # Itaobim
  3134004,  # Itinga
  3139201,  # Malacacheta
  3141405,  # Medina
  3141801,  # Minas Novas
  3148707,  # Pedra Azul
  3168606,  # Teófilo Otoni
  3169703,  # Turmalina
  3156502,  # Rubelita
  3171600,  # Virgem da Lapa
  3157005  # Salinas
)
 

#-------------tabela 01

tabela01_ambiental<-  pop %>%  left_join(df_nome)  %>%   select(Municipio, IBGE7, ANO,AREA,D_DENSP) %>%filter(IBGE7 %in% municipios_vale & ANO== 2021) %>% select(Municipio, everything())  




saveRDS(tabela01_ambiental, 'dados/tabela01_ambiental.rds')


#-------------tabela 02


tabela02_ambiental<-  meio_ambiente %>%  left_join(df_nome)  %>%   select(Municipio, IBGE7, ANO,M_REFLO,M_FLONATIVA,M_INFRA,M_AGRO) %>%mutate(outros = 100 - sum(M_REFLO, M_FLONATIVA, M_INFRA, M_AGRO)) %>%filter(IBGE7 %in% municipios_vale & ANO== 2021) %>% select(Municipio, everything())  


saveRDS(tabela02_ambiental, 'dados/tabela02_ambiental.rds')



#-------------tabela 03 - Densidade de veículos
tabela03_ambiental<-  meio_ambiente %>%  left_join(df_nome)  %>%   select(Municipio, IBGE7, ANO,M_FROTA, M_BOVINO, M_FOCOS,M_CANA) %>%filter(IBGE7 %in% municipios_vale & ANO== 2021) %>% select(Municipio, everything()) 


saveRDS(tabela03_ambiental, 'dados/tabela03_ambiental.rds')

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#-------------------------------plot tabela 01
library(tidyverse)
library(gt)

tabela01_ambiental <- readRDS("dados/tabela01_ambiental.rds")
df_nome <- readRDS("dados/df_nome.rds")

tabela01_ambiental  %>% 
  gt() %>% 
  tab_header(
    title = "Ambiental",
  )%>%
  opt_align_table_header(align = "left") %>%
  tab_stubhead(label = md("Region and <br />IAP Type")) %>%
  tab_style(
    style = cell_text(size = "smaller"),
    locations = cells_body()
  )  %>% #rótulo
  opt_table_font(font = google_font(name = "Karla")) %>% 
  tab_options(data_row.padding = px(6),
              heading.align = 'left',
              column_labels.background.color = 'dodgerblue4',
              heading.title.font.size = px(26)) %>% 
  tab_style(
    style = cell_text(
      color = 'dodgerblue4', 
      weight = 'bold', 
      font = google_font('Merriweather')
    ),
    locations = cells_title(groups = 'title')
  ) %>%
  cols_label(
    AREA = 'Área Municipal',
    D_DENSP = 'Densidade Populacional'
  )   %>% 
  fmt_number(
    columns = 5,  # Seleciona colunas
    decimals = 2)  # Definir 2 casas decimais 




```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

#-------------------------------plot tabela 02
library(tidyverse)
library(gt)

tabela02_ambiental <- readRDS("dados/tabela02_ambiental.rds")
df_nome <- readRDS("dados/df_nome.rds")

tabela02_ambiental  %>% 
  gt() %>% 
  tab_header(
    title = "Ambiental",
  )%>%
  opt_align_table_header(align = "left") %>%
  tab_stubhead(label = md("Region and <br />IAP Type")) %>%
  tab_style(
    style = cell_text(size = "smaller"),
    locations = cells_body()
  )  %>% #rótulo
  opt_table_font(font = google_font(name = "Karla")) %>% 
  tab_options(data_row.padding = px(6),
              heading.align = 'left',
              column_labels.background.color = 'dodgerblue4',
              heading.title.font.size = px(26)) %>% 
  tab_style(
    style = cell_text(
      color = 'dodgerblue4', 
      weight = 'bold', 
      font = google_font('Merriweather')
    ),
    locations = cells_title(groups = 'title')
  ) %>%
  cols_label(
    M_REFLO = 'cobertura vegetal por área plantada',
    M_FLONATIVA = 'cobertura vegetal por flora nativa',
    M_INFRA = 'infraestrutura urbana',
    M_AGRO = 'agropecuária'
  ) 




```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

#-------------------------------plot tabela 03
library(tidyverse)
library(gt)

tabela03_ambiental <- readRDS("dados/tabela03_ambiental.rds")
df_nome <- readRDS("dados/df_nome.rds")

tabela03_ambiental  %>% 
  gt() %>% 
  tab_header(
    title = "Ambiental",
  )%>%
  opt_align_table_header(align = "left") %>%
  tab_stubhead(label = md("Region and <br />IAP Type")) %>%
  tab_style(
    style = cell_text(size = "smaller"),
    locations = cells_body()
  )  %>% #rótulo
  opt_table_font(font = google_font(name = "Karla")) %>% 
  tab_options(data_row.padding = px(6),
              heading.align = 'left',
              column_labels.background.color = 'dodgerblue4',
              heading.title.font.size = px(26)) %>% 
  tab_style(
    style = cell_text(
      color = 'dodgerblue4', 
      weight = 'bold', 
      font = google_font('Merriweather')
    ),
    locations = cells_title(groups = 'title')
  ) %>%
  cols_label(
    M_FROTA = 'Densidade de veículos',
    M_BOVINO = 'Densidade de Bovinos',
    M_FOCOS = 'Focos de Calor',
    M_CANA = 'Área de cobertura plantação de Açucar'
  ) 



```
