---
title: "Ações prioritárias para o desenvolvimento"
authors: 
- Caio Gonçalves 
- Cláudio Shikida
---

```{css}
#| echo: false
p {
  text-align: justify
}
```

## O que dizem os planos de desenvolvimento realizados para a região sobre o lítio e as questões sociais?

<!-- A utilização da matriz insumo-produto (MIP) para a análise regional e o cálculo de índices de ligação enriquecem consideravelmente nossa compreensão do impacto econômico da mineração nos municípios do Norte e Nordeste de Minas Gerais. De acordo com o estudo de Souza, Gonçalves e Franco (2015), que se baseou na MIP de 2008 de Minas Gerais, setores-chave como "indústria extrativa mineral", "alimentos e bebidas", "produtos químicos", "fabricação de aço e derivados" e "serviços de informação" foram identificados. -->

O Norte e o Nordeste de Minas Gerais destacam-se como áreas promissoras para a mineração, especialmente na extração de lítio. O potencial de produção de lítio já havia sido indicado em estudos para região como o Plano de Desenvolvimento para o Vale do Jequitinhonha [@fjp2017]. Isto significa que a criação do Vale do Lítio pode ser uma oportunidade para o desenvolvimento da região que em termos industriais, há nichoscom potencial de desenvolvimento para a região, como a fabricação de alimentos e construção civil conforme estudo de setores-chave utilizando matriz insumo-produto da Região Intermediária de Teófilo Otoni [@fjp2023].

Possíveis estratégias de desenvolvimento para estes municípios relacionados ao lítio (e à mineração) incluem:

-   **Fortalecimento da Indústria Local**: Foco especial na cadeia produtiva do lítio, incentivando seu processamento na região para agregar valor ao produto. Isso envolve a internalização de toda a cadeia, desde a extração até a fabricação de baterias, representando uma chance significativa para o avanço econômico e industrial local, utilizando os recursos naturais para gerar emprego e aumentar a receita, contribuindo para um crescimento econômico sustentável.

-   **Atenção aos Desafios Ambientais e Sociais**: Considerar os impactos ambientais e sociais da mineração, como o despejo de efluentes tóxicos e a poluição do ar e do solo, que podem causar doenças graves e prejudicar a agricultura. A atenção deve se estender além dos municípios do Vale, alcançando áreas adjacentes e ao longo dos rios. Assim, é vital que a mineração seja conciliada com a proteção ambiental.

-   **Melhoria do Ambiente de Negócios**: Conforme dados atualizados até 2024, dos 14 municípios do Vale do Lítio, apenas 6 deles sancionaram uma versão municipal da Lei de Liberdade Econômica, quais sejam, Rubelita, Salinas, Malacacheta, Medina, Minas Novas e Turmalina. Como se sabe, a Lei de Liberdade Econômica é um instrumento facilitador da abertura de novos negócios, notadamente aqueles que envolvem baixo risco (a listagem das 701 atividades, conforme a legislação mineira, encontra-se no Anexo I da Resolução 02 de 13 de maio de 2021). Estudos mostram que a melhora no ambiente de negócios tem impacto positivo na prosperidade local (ver, por exemplo, Cavalcante 2015).

-   **Articulação Institucional**: O sucesso de uma política pública no denominado Vale do Lítio depende de uma articulação governamental com governos locais, populações e com o governo federal. A exploração do lítio, de forma ambientalmente eficaz e com um ambiente de negócios favorável tem potencial para uma geração de empregos que não se percam no médio prazo. O alinhamento dos interesses é necessário não apenas para o início do projeto, mas também para seu bom andamento.

Conforme indicado no Plano de Desenvolvimento para o Vale do Jequitinhonha [@fjp2017], as ações prioritárias para o desenvolvimento social levantadas à época no estudo foram:

### Educação

-   Criar programas de bolsas de estudos nos moldes do Projovem Campo - Saberes de Minas, com monitoramento das escolas e das Superintendências Regionais de Educação (SRE), para os anos finais do ensino do fundamental, ensino médio e Educacão de Jovens e Adultos (EJA);

-   Criar programa de acompanhamento e reforço nas escolas para os alunos com dificuldade de aprendizagem, principalmente nos anos iniciais do ensino fundamental;

-   Capacitar os professores, gestores e técnicos das redes estaduais e municipais, em suas respectivas áreas de atuação, conforme os níveis e modalidades de ensino, principalmente nas modalidades do campo, alfabetização e Educação de Jovens e Adultos (EJA);

-   Rever o sistema de nucleação das escolas, com vistas à alteração do modelo atual e como estratégia para o atendimento das criancas de 4 e 5 anos;

-   Ampliar a metodologia da educação do campo nas escolas públicas, com adequação dos currículos e calendários à demanda do meio rural, avaliando a possibilidade de adotar em algumas escolas metodologias similares às adotadas nas Escolas Família Agrícolas (EFA);

-   Ofertar cursos de qualificação (Formação Inicial Continuada) para os alunos dos anos finais do ensino fundamental, do ensino médio e do EJA, em horários que sejam adequados para esses alunos. Os cursos devem ser ofertados com continuidade e diversidade, em consonância às potencialidades econômicas da região e à capilaridade territorial, incluindo a qualificação para o trabalho no campo.

### Saúde

-   Apoiar a expansão da cobertura das Equipes de Saúde da Família (ESF) no meio rural por meio de unidades móveis com equipe itinerante para atender as comunidades mais distantes;

-   Estimular a implantação de protocolos assistenciais, que valorizem a atenção programada, a priorização do atendimento e o encaminhamento de modo adequado;

-   Apoiar os municípios na organização dos sistemas locais de Vigilância em Saúde;

-   Implementar os Centro de Especialidade Médicas (CEM) nos territórios do Jequitinhonha, confomie previstos pela SES-MG;

-   Concluir o Hospital Regional de Teófilo Otoni e construir o segundo hospital regional previsto para a região;

-   Implementar programas de capacitação dos gestores municipais no que diz respeito aos instrumentos de planejamento, à gestão financeira e orçamentária e ao controle social no SUS.

### Assistência Social

-   Introduzir novos conteúdos e metodologias de intervenção socioassistenciais para o público adolescente e jovem, bem como ações que visem coibir a violação de direitos;

-   Promover ações de esclarecimento da sociedade e da população idosa em relação aos seus direitos, associadas a intervenções que coíbam a intermediação de terceiros para o requerimento de benefícios;

-   Criar mecanismos para uma articulação permanente e mais eficiente com as entidades socioassistenciais existentes visando à troca de experiências com os órgãos públicos da assistência social;

-   Promover a integração das ações da assistência social que demandam intervenções intersetoriais envolvendo educação, saúde, cultura, direitos humanos, desenvolvimento agrário e meio ambiente.

### Segurança pública

-   Incrementar a infraestrutura, os recursos logísticos e os efetivos da Polícia Civil (todas as carreiras);

-   Incrementar a infraestrutura, os recursos logísticos e os efetivos da Polícia Militar (com ênfase em implementação de unidades de Patrulhas Rurais);

-   Criar espaços interinstitucionais de interlocucão entre Poder Público Estadual, Municipal (Prefeituras e Câmaras de Vereadores), Poder Judiciário e Forças de Segurança Pública, por meio do incentivo à críacão de Gabinetes de Gestão Integrada Municipal de Segurança Pública (GGIM-SP) nos municípios-sede de microterritórios;

-   Construir Centros Socioeducativos para o cumprimento de medidas de internação nos municípios de Araçuaí e Medina;

-   Auxiliar a produção e elaboração de Planos Municipais de Segurança Pública em municípios-sede de microterritórios. A ênfase deve ser dada principalmente em políticas de prevenção, organizando e articulando instituições de assistência social e de educacâo, associações de bairro, entre outras.

### Saneamento e habitação

-   Fomentar a formação/capacitação de gestores, gerentes e atores sociais municipais em relação a política pública de saneamento básico e ambiental;

-   Oferecer apoio técnico e financeiro à elaboração e revisão dos Planos Municipais de Saneamento Básico (PMSB);

-   Oferecer apoio técnico e financeiro à implementação institucional dos PMSB;

-   Oferecer apoio técnico e financeiro à elaboração dos Planos Municipais de Saneamento Rural (PMSR);

-   Promover a articulação interinstitucional para a ampliação e melhoria da atuação da COPASA e COPANOR nos territórios;

-   Fomentar a implantação do Sistema de Vigilância da Qualidade da Água para o Consumo Humano no âmbito municipal;

-   Fomentar a elaboração, revisão ou adequação dos Planos Municipais de Habitação Social e de Regularização Fundiária;

-   Fomentar a instalação dos Conselhos Municipais de Habitação ou outras instâncias que possibilitem o fortalecimento do controle social;

-   Estimular a utilização de mão de obra local na construção e/ou reforma de unidades habitacionais, sobretudo no formato de autoconstrução;

-   Fomentar a melhoria e o provimento de infraestrutura urbana nos domicílios inadequados com relação a módulos sanitários, reformas, energia elétrica, abastecimento de água, esgotamento sanitário e coleta de lixo, com especial atenção à redução dos déficits nas zonas rurais;

-   Fomentar a capacitação de gestores e conselheiros municipais, objetivando o fortalecimento da política pública municipal e o empoderamento municipal para implementação das políticas públicas de habitação social.

A análise feita anteriormente, embora não permita um comentário técnico mais detalhado sobre cada um dos tópicos acima, mostra que a realidade das cidades do Vale do Lítio e, de forma mais geral, do Vale do Jequitinhonha não se alterou tanto desde 2017 o que, se por um lado, é motivo de preocupação, fica claro que há espaço para políticas públicas que transformem as 14 cidades e seu entorno em uma vitrine da administração estadual para o restante da Federação.

### Considerações finais

Um plano de ação pode transformar essa região de Minas Gerais em um importante polo industrial, centrado na exploração do lítio. Diante da crescente demanda por baterias desse material, a região tem potencial para se tornar um *hub* estratégico na produção desses materiais. O desenvolvimento não apenas impulsionará a economia local, mas também posicionará a região como um fornecedor-chave de lítio e seus derivados no mercado global. Para isso, é essencial desenvolver políticas que agreguem valor, levando em conta tanto as oportunidades econômicas quanto as responsabilidades ambientais e sociais inerentes à atividade mineradora. Existem uma série de ações já indicadas que melhorariam o desenolvimento social em estudos prévios para região e podem ser verificados a viabilidade para os municípios do vale do Lítio.

<!-- Esta análise revela uma mudança significativa na dinâmica produtiva da região, marcada pela expansão da atividade mineradora, com destaque para a extração de granito, grafita e, especialmente, lítio, principalmente no Médio Jequitinhonha. Essas atividades se tornaram uma fonte relevante de empregos e receitas para muitos municípios. A atividade cafeeira também manteve sua importância como um motor de dinamismo e geração de empregos. -->

<!-- No microterritório de Araçuaí, a extração mineral, especialmente de lítio e granito, tem um papel significativo. Em 2014, o Valor Adicionado da indústria representou 9,9% do PIB de Araçuaí, com a construção civil e a extração mineral sendo os principais contribuintes. A Companhia Brasileira de Lítio (CBL) tem uma presença marcante na região, com a extração de lítio na mina Cachoeira, situada no município de Araçuaí. Além disso, a transformação industrial, especialmente na indústria química, constitui uma parte significativa da atividade, com foco na produção de concentrados de lítio. -->

<!-- O microterritório de Araçuaí é notável por sua variedade de recursos minerais, incluindo lítio, granito, gemas, feldspato, calcita, ardósia, quartzo cristal, areias industriais, xisto, turmalina, diamante secundário, além de areia e argila. A região detém 100% das reservas de lítio (espodumênio e petalita), com a maior parte localizada em Itinga, mas também em Araçuaí, e 41% das reservas de granito. -->

<!-- Em 2013, a grafita, o granito e o lítio responderam por 95% da arrecadação da Compensação Financeira pela Exploração de Recursos Minerais (CFEM) no Médio/Baixo Jequitinhonha. A arrecadação de CFEM em Pedra Azul foi significativa, principalmente devido à extração de grafita e granito, enquanto Araçuaí também teve uma arrecadação considerável, principalmente proveniente do granito e do lítio. -->

<!-- Diante desses desafios, é fundamental buscar um equilíbrio entre o desenvolvimento econômico e a preservação ambiental. A mineração, especialmente com a descoberta de novas jazidas de lítio e as oportunidades em pedras ornamentais, gemas e joias, pode ser uma fonte significativa de empregos e geração de valor. Para isso, é necessário mapear áreas potenciais e atualizar informações sobre produção e reservas.  -->

<!-- Ademais, há uma oportunidade clara de agregar valor à produção local, particularmente no que se refere ao lítio e à grafita. Isso implica desafios em termos de governança e a necessidade de apoio institucional forte. No caso específico das gemas e joias, isso significa investir em pesquisa, formação de mão de obra qualificada, aquisição de tecnologia para o processamento das pedras, e avançar em governança e apoio institucional. -->

<!-- Por fim, a proposta de verticalizar a cadeia produtiva do lítio no território, incluindo a instalação de fábricas de baterias, representa uma oportunidade para gerar mais valor internamente e contribuir para o desenvolvimento sustentável da região. Isso envolve a criação de políticas de agregação de valor, que considerem tanto as potencialidades econômicas quanto os imperativos ambientais e sociais da mineração. -->
