# Ficha Técnica {.unnumbered}

<br> <br>

**GOVERNADOR DO ESTADO DE MINAS GERAIS**

Romeu Zema Neto

**SECRETÁRIA DE ESTADO DE PLANEJAMENTO E GESTÃO**

Luísa Cardoso Barreto

<br>

**FUNDAÇÃO JOÃO PINHEIRO (FJP)**

Presidente

Helger Marra Lopes

Vice-Presidente

Mônica Moreira Esteves Bernardi

<br>

**DIRETORIA DE ESTATÍSTICA E INFORMAÇÕES (Direi)**

Claudio Djissey Shikida (Diretor)

Tomaz Duarte Moreira (Coordenador-Geral)

**Coordenação de Indicadores Sociais (CCR)**

Caio Gonçalves

<br>

**Organizadores**

Caio Gonçalves

Vitor Marinho

**Autores**

- Cap. 1: População e estrutura etária - Caio Gonçalves e Vitor Marinho

- Cap. 2: Produção e Emprego - Vitor Marinho, Caio Gonçalves e Cláudio Shikida

- Cap. 3: Aspectos Sociais - Caio Gonçalves e Vitor Marinho

- Cap. 4: Fluxos Migratórios com dados censitários - Olinto Nogueira

- Cap. 5: Migração com CadÚnico Autores - Helena Soares

- Cap. 6: Caso Araçuaí - Cláudio Costa e Helena Soares

- Cap. 7: Equipamentos de saúde e educação- Caio Gonçalves, Vitor Marinho e Cláudio Shikida

- Cap. 8: Ações prioritárias de desenvolvimento - Caio Gonçalves e Cláudio Shikida

Os textos produzidos contaram com revisões e comentários de Renato Vale, Cláudio Costa e Cláudio Shikida.


**Capa**

\[\]

**Revisão**

\[\]

**Normalização**

\[\]

### Detalhes do livro

-   **Tipo:** eBook

-   **ISBN:** \[solicitar\]

-   **Ano da Edição:** 2024
