# Prefácio {.unnumbered}

O propósito deste documento é fornecer informações relacionadas às características demográficas e socioeconômicas dos municípios que possuem potencial de exploração do lítio no Vale do Jequitinhonha. De forma simples e direta, este livro digital aborda uma gama de temas essenciais, incluindo dados demográficos, produção, emprego, vulnerabilidade, educação, saúde e saneamento básico. Além disso, destaca elementos identificados nos planos de desenvolvimento elaborados para a região em estudo.

Para garantir a qualidade das informações, utilizou-se os dados sistematizados na Plataforma do Índice Mineiro de Responsabilidade Social [IMRS](https://imrs.fjp.mg.gov.br/) da Fundação João Pinheiro, onde também é possível acessar perfis individuais de cada município [aqui](https://imrs.fjp.mg.gov.br/Perfil). As fontes de dados provêm de diversas origens, incluindo os dados mais recentes do Censo Demográfico de 2022 realizado pelo Instituto Brasileiro de Geografia e Estatística (IBGE).

**Perguntas orientadoras**:

Este prefácio também serve como um guia para as principais questões que o documento busca responder:

1.  [Quantas pessoas residem nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? Qual foi a evolução populacional nos últimos 12 anos?](1_Demografia.qmd#sec-residentes)

2.  [Qual é a estrutura etária atual dos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? A população é predominantemente jovem ou envelhecida?](1_Demografia.qmd#sec-estrutura-etaria)

3.  [Quais os movimentos migratórios observados nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? É possível inferir sobre a última década sem os dados do Censo Demográfico de 2022?](temp1.qmd#sec-mig-censo)

4.  O que os dados do CadÚnico podem revelar sobre o a população em idade ativa e migração? [link](temp2.qmd#sec-cad-unico)

5.  Quais os fluxos migratórios observados especificamente em Araçuaí? [link](temp3.qmd#sec-fluxo-aracuai)

6.  Em termos da importância econômica das atividades presentes nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha, o que os dados dos PIB revelam? [link](2_Economia.qmd#sec-qt1-economia)

7.  Qual o quadro atual das exportações dos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? [link](2_Economia.qmd#sec-exportacao)

8.  Qual a importância da indústria extrativa na geração de empregos formais nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha? [link](2_Economia.qmd#sec-emprego-formal)

9.  Como está a situação social nos municípios com potencial para exploração do lítio no Vale do Jequitinhonha de maneira geral? [link](3_Social.qmd#sec-social-geral)

10. O que revelam os principais indicadores da área da educação, saúde, assistência social, segurança pública e saneamento básico? [link](3_Social.qmd#sec-indicador-educ)

11. 

12. Qual a situação desses municípios em termos de equipamentos de saúde e educação? [link](3a_equipamentos_publicos.qmd#sec-equip-publico)

13. O que dizem os planos de desenvolvimento realizados para a região sobre o lítio e as questões sociais? [link](5_Acoes.qmd#sec-acoe-desv)
